export const SET_SOCKET = "SET_SOCKET";
export const SET_OWNER = "SET_OWNER";
export const ADD_JOIN_REQUEST = "ADD_JOIN_REQUEST";
export const ADD_JOINED_PLAYER = "ADD_JOINED_PLAYER";
export const SET_JOINED_PLAYERS = "SET_JOINED_PLAYERS";
export const SET_GAME_START = "SET_GAME_START";
export const REMOVE_JOIN_REQUEST = "REMOVE_JOIN_REQUEST";